#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.3.3 effective-5.10 (swiftlang-6.3.3.1.3 clang-2100.1.1.101)
#ifndef ALOGAMEKYCKIT_SWIFT_H
#define ALOGAMEKYCKIT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AlogameKycKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import ObjectiveC;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AlogameKycKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

/// <code>.dev</code> | <code>.prod</code> — selects between the two compile-time base URLs. There
/// is no way for a Host_App to supply a URL directly (R5.3/R5.3a). See
/// <code>Internal/Net/Environment.swift</code> for the actual constants.
/// <code>@objc</code>-backed by <code>Int</code> (not the raw-value-less enum this started as) so
/// it can appear in the Objective-C-facing overloads on <code>AlogameKycSdk</code> —
/// same pattern v2’s <code>OEGActionType</code>/<code>OEGIAPStatus</code> use
/// (<code>Core/Public/OEGEnums.swift</code>). Purely additive: no existing Swift call
/// site reads <code>.rawValue</code>, so <code>.dev</code>/<code>.prod</code>/exhaustive switches are
/// unaffected.
typedef SWIFT_ENUM(NSInteger, AlogameKycEnv, open) {
  AlogameKycEnvDev = 0,
  AlogameKycEnvProd = 1,
};

/// The Objective-C-facing mirror of <code>AlogameKycFailReason</code> — <code>@objc enum</code>
/// only accepts an <code>Int</code> raw type, so the existing <code>String</code>-backed enum
/// above (its raw values are load-bearing — R7.1 Android-identifier parity,
/// asserted by <code>PublicSurfaceTests.test_alogameKycFailReason_...</code>) stays
/// exactly as it is rather than being retyped. <code>AlogameKycObjcListener</code>
/// (the <code>@objc</code>-facing listener protocol) carries this instead of the
/// String-backed original. Case order/count is asserted alongside the
/// Swift enum’s own parity test — a 10th reason added to one without the
/// other fails there, not here.
typedef SWIFT_ENUM(NSInteger, AlogameKycFailReasonCode, open) {
  AlogameKycFailReasonCodeNotInitialized = 0,
  AlogameKycFailReasonCodeNoGameRole = 1,
  AlogameKycFailReasonCodeSessionUnavailable = 2,
  AlogameKycFailReasonCodeSessionInvalid = 3,
  AlogameKycFailReasonCodeOtpAttemptsExceeded = 4,
  AlogameKycFailReasonCodeOtpUnavailable = 5,
  AlogameKycFailReasonCodeRateLimited = 6,
  AlogameKycFailReasonCodeServiceUnavailable = 7,
  AlogameKycFailReasonCodeUnknownError = 8,
};

SWIFT_ENUM_FWD_DECL(NSInteger, AlogameKycResultStatus)
@class NSString;
/// The Objective-C-facing counterpart to <code>AlogameKycListener</code> — same
/// pattern as v2’s <code>OEGCallback</code>/<code>OEGPushDelegate</code>
/// (<code>Core/Bridge/OEGCallback.swift</code>, <code>Core/Push/OEGPush.swift</code>): an
/// <code>@objc protocol</code> with <code>@objc optional</code> for the one method that isn’t
/// mandatory, since a Swift protocol-extension default implementation
/// (what <code>AlogameKycListener.onSessionTokenNeeded</code> uses) has no Objective-C
/// equivalent and is never visible across the bridge.
/// <code>AlogameKycResult</code>’s enum-with-payload cannot cross into an <code>@objc</code>
/// protocol at all — <code>onResult</code> here carries <code>AlogameKycResultStatus</code> plus
/// separate <code>reason</code>/<code>message</code> parameters instead (<code>reason</code> is only
/// meaningful when <code>status == .failed</code>, same discipline
/// <code>AlogameKycResult.failed</code> itself already has).
SWIFT_PROTOCOL("_TtP13AlogameKycKit22AlogameKycObjcListener_")
@protocol AlogameKycObjcListener
/// Fires exactly once per <code>show</code> call, on the main queue — same timing
/// guarantee as <code>AlogameKycListener.onResult</code> (R3.2).
- (void)onResultWithStatus:(enum AlogameKycResultStatus)status reason:(enum AlogameKycFailReasonCode)reason message:(NSString * _Nullable)message;
@optional
/// Only invoked when <code>AlogameKycConfig.tokenProvider</code> was <code>nil</code> at
/// <code>initialize</code>. Optional here the Objective-C way (<code>@objc optional</code>,
/// checked via <code>responds(to:)</code>/optional chaining) rather than a Swift
/// protocol-extension default, since defaults do not bridge.
- (void)onSessionTokenNeededForUid:(NSString * _Nonnull)uid;
@end

/// The Objective-C-facing discriminant for <code>AlogameKycResult</code> — <code>@objc</code>
/// cannot apply to an enum with associated values at all (no Objective-C
/// equivalent exists for <code>.failed(reason:, message:)</code>), so this package’s
/// only public enum-with-payload stays exactly as it is for Swift callers.
/// <code>AlogameKycObjcListener.onResult</code> carries this plus separate <code>reason</code>/
/// <code>message</code> parameters instead — same flattening v2 uses for
/// <code>OEGIAPStatus</code>/<code>OEGAccountCallback</code> (<code>Core/Public/OEGEnums.swift</code>) rather
/// than a wrapper class with optional fields.
typedef SWIFT_ENUM(NSInteger, AlogameKycResultStatus, open) {
  AlogameKycResultStatusSuccess = 0,
  AlogameKycResultStatusFailed = 1,
  AlogameKycResultStatusCancelled = 2,
};

@class UIViewController;
/// The entire public API (design.md § Public API — exactly this surface,
/// R2.1). Everything else in this module is <code>internal</code>.
/// <code>show</code> runs prerequisite checks and the <code>xmdtCompleted</code> short-circuit
/// synchronously against <code>FlowController</code>, and only presents
/// <code>KycViewController</code> once the flow actually needs a screen — never for the
/// transient <code>.resolving</code> tick, so a session that resolves straight to
/// <code>xmdtCompleted</code> opens no screen at all (R2.4 of the iOS spec). <code>onResult</code>
/// is deferred until <code>KycViewController</code> has actually been dismissed
/// (<code>notifyViewControllerDismissed</code>, called from its <code>dismiss(animated:)</code>
/// completion) whenever a screen was shown at all — see <code>onFlowStateChanged</code>.
/// <code>@objc</code> + <code>NSObject</code> added directly onto this same class — same
/// mechanism v2 uses for <code>OEGManager</code>/<code>OegSdkCore</code>
/// (<code>Core/Public/OEGManager.swift</code>, <code>Core/Public/OegSdkCore.swift</code>): no
/// separate ObjC-facing facade class, <code>@objc</code> annotations live right on
/// the existing public members. Every member already ObjC-representable
/// (<code>String</code>/<code>String?</code>/<code>Bool</code>/closures of those) just gets <code>@objc</code>
/// directly; the two members that were not representable at all
/// (<code>initialize(_:)</code> takes a struct, <code>show(from:listener:)</code> takes a
/// protocol carrying an enum-with-payload) get a parallel <code>@objc</code> overload
/// instead of having their existing Swift signature changed — this
/// package’s public API is documented as frozen (design.md § Public API,
/// guarded by <code>PublicSurfaceTests.swift</code>), unlike v2 which had no prior
/// Swift-only surface to preserve.
SWIFT_CLASS("_TtC13AlogameKycKit13AlogameKycSdk")
@interface AlogameKycSdk : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AlogameKycSdk * _Nonnull shared;)
+ (AlogameKycSdk * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Objective-C-facing overload — <code>AlogameKycConfig</code> is a <code>struct</code>
/// (can’t cross the bridge at all), so this takes the same two fields
/// as plain, ObjC-representable parameters instead and builds the
/// config internally. Behaves identically to <code>initialize(_:)</code>.
- (void)initializeWithEnv:(enum AlogameKycEnv)env tokenProvider:(void (^ _Nullable)(NSString * _Nonnull, void (^ _Nonnull)(NSString * _Nullable)))tokenProvider;
/// <code>uid</code> and <code>sessionToken</code> are required together — they always arrive
/// from the same game-server response. Switching to a different <code>uid</code>
/// clears the verified cache and the prefill name for the old one — see
/// <code>SessionHolder.setGameRole</code>.
- (void)setGameRoleWithUid:(NSString * _Nonnull)uid sessionToken:(NSString * _Nonnull)sessionToken serverId:(NSString * _Nullable)serverId roleId:(NSString * _Nullable)roleId;
/// In-memory only — never written to disk, never sent anywhere except to
/// <code>ekycx</code> at the collect step, and only after the player has seen and
/// could edit it. Cleared when <code>uid</code> changes.
/// <code>ASAuthorizationAppleIDCredential.fullName</code> arrives only on the
/// <em>first</em> authorize for a given Apple ID — capture it there or it is
/// gone until the user revokes the app in Settings.
- (void)setPrefill:(NSString * _Nullable)fullName;
/// RAM cache of the most recent successful flow for the current uid —
/// <em>not</em> an authorization source. The game server must call
/// <code>POST /xmdt/user-status</code> before trusting that a player has verified;
/// a modified client can make this return whatever it wants.
@property (nonatomic, readonly) BOOL isVerified;
/// Delegates to the pending token request, if any. Ignored (not thrown) when nothing is awaiting a token.
- (void)provideSessionToken:(NSString * _Nonnull)token;
/// Delegates to the pending token request, if any — resolves it as <code>.sessionUnavailable</code>.
- (void)abortPendingToken;
/// Objective-C-facing overload — <code>AlogameKycListener</code> can’t cross the
/// bridge itself (<code>onResult</code> carries <code>AlogameKycResult</code>, an enum with
/// associated values), so this wraps <code>objcListener</code> in
/// <code>ObjcListenerAdapter</code> and calls the exact same <code>show(from:listener:)</code>
/// above. No behavior lives here beyond that translation.
- (void)showFromViewController:(UIViewController * _Nonnull)viewController objcListener:(id <AlogameKycObjcListener> _Nonnull)objcListener;
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.3.3 effective-5.10 (swiftlang-6.3.3.1.3 clang-2100.1.1.101)
#ifndef ALOGAMEKYCKIT_SWIFT_H
#define ALOGAMEKYCKIT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AlogameKycKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import ObjectiveC;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AlogameKycKit",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

/// <code>.dev</code> | <code>.prod</code> — selects between the two compile-time base URLs. There
/// is no way for a Host_App to supply a URL directly (R5.3/R5.3a). See
/// <code>Internal/Net/Environment.swift</code> for the actual constants.
/// <code>@objc</code>-backed by <code>Int</code> (not the raw-value-less enum this started as) so
/// it can appear in the Objective-C-facing overloads on <code>AlogameKycSdk</code> —
/// same pattern v2’s <code>OEGActionType</code>/<code>OEGIAPStatus</code> use
/// (<code>Core/Public/OEGEnums.swift</code>). Purely additive: no existing Swift call
/// site reads <code>.rawValue</code>, so <code>.dev</code>/<code>.prod</code>/exhaustive switches are
/// unaffected.
typedef SWIFT_ENUM(NSInteger, AlogameKycEnv, open) {
  AlogameKycEnvDev = 0,
  AlogameKycEnvProd = 1,
};

/// The Objective-C-facing mirror of <code>AlogameKycFailReason</code> — <code>@objc enum</code>
/// only accepts an <code>Int</code> raw type, so the existing <code>String</code>-backed enum
/// above (its raw values are load-bearing — R7.1 Android-identifier parity,
/// asserted by <code>PublicSurfaceTests.test_alogameKycFailReason_...</code>) stays
/// exactly as it is rather than being retyped. <code>AlogameKycObjcListener</code>
/// (the <code>@objc</code>-facing listener protocol) carries this instead of the
/// String-backed original. Case order/count is asserted alongside the
/// Swift enum’s own parity test — a 10th reason added to one without the
/// other fails there, not here.
typedef SWIFT_ENUM(NSInteger, AlogameKycFailReasonCode, open) {
  AlogameKycFailReasonCodeNotInitialized = 0,
  AlogameKycFailReasonCodeNoGameRole = 1,
  AlogameKycFailReasonCodeSessionUnavailable = 2,
  AlogameKycFailReasonCodeSessionInvalid = 3,
  AlogameKycFailReasonCodeOtpAttemptsExceeded = 4,
  AlogameKycFailReasonCodeOtpUnavailable = 5,
  AlogameKycFailReasonCodeRateLimited = 6,
  AlogameKycFailReasonCodeServiceUnavailable = 7,
  AlogameKycFailReasonCodeUnknownError = 8,
};

SWIFT_ENUM_FWD_DECL(NSInteger, AlogameKycResultStatus)
@class NSString;
/// The Objective-C-facing counterpart to <code>AlogameKycListener</code> — same
/// pattern as v2’s <code>OEGCallback</code>/<code>OEGPushDelegate</code>
/// (<code>Core/Bridge/OEGCallback.swift</code>, <code>Core/Push/OEGPush.swift</code>): an
/// <code>@objc protocol</code> with <code>@objc optional</code> for the one method that isn’t
/// mandatory, since a Swift protocol-extension default implementation
/// (what <code>AlogameKycListener.onSessionTokenNeeded</code> uses) has no Objective-C
/// equivalent and is never visible across the bridge.
/// <code>AlogameKycResult</code>’s enum-with-payload cannot cross into an <code>@objc</code>
/// protocol at all — <code>onResult</code> here carries <code>AlogameKycResultStatus</code> plus
/// separate <code>reason</code>/<code>message</code> parameters instead (<code>reason</code> is only
/// meaningful when <code>status == .failed</code>, same discipline
/// <code>AlogameKycResult.failed</code> itself already has).
SWIFT_PROTOCOL("_TtP13AlogameKycKit22AlogameKycObjcListener_")
@protocol AlogameKycObjcListener
/// Fires exactly once per <code>show</code> call, on the main queue — same timing
/// guarantee as <code>AlogameKycListener.onResult</code> (R3.2).
- (void)onResultWithStatus:(enum AlogameKycResultStatus)status reason:(enum AlogameKycFailReasonCode)reason message:(NSString * _Nullable)message;
@optional
/// Only invoked when <code>AlogameKycConfig.tokenProvider</code> was <code>nil</code> at
/// <code>initialize</code>. Optional here the Objective-C way (<code>@objc optional</code>,
/// checked via <code>responds(to:)</code>/optional chaining) rather than a Swift
/// protocol-extension default, since defaults do not bridge.
- (void)onSessionTokenNeededForUid:(NSString * _Nonnull)uid;
@end

/// The Objective-C-facing discriminant for <code>AlogameKycResult</code> — <code>@objc</code>
/// cannot apply to an enum with associated values at all (no Objective-C
/// equivalent exists for <code>.failed(reason:, message:)</code>), so this package’s
/// only public enum-with-payload stays exactly as it is for Swift callers.
/// <code>AlogameKycObjcListener.onResult</code> carries this plus separate <code>reason</code>/
/// <code>message</code> parameters instead — same flattening v2 uses for
/// <code>OEGIAPStatus</code>/<code>OEGAccountCallback</code> (<code>Core/Public/OEGEnums.swift</code>) rather
/// than a wrapper class with optional fields.
typedef SWIFT_ENUM(NSInteger, AlogameKycResultStatus, open) {
  AlogameKycResultStatusSuccess = 0,
  AlogameKycResultStatusFailed = 1,
  AlogameKycResultStatusCancelled = 2,
};

@class UIViewController;
/// The entire public API (design.md § Public API — exactly this surface,
/// R2.1). Everything else in this module is <code>internal</code>.
/// <code>show</code> runs prerequisite checks and the <code>xmdtCompleted</code> short-circuit
/// synchronously against <code>FlowController</code>, and only presents
/// <code>KycViewController</code> once the flow actually needs a screen — never for the
/// transient <code>.resolving</code> tick, so a session that resolves straight to
/// <code>xmdtCompleted</code> opens no screen at all (R2.4 of the iOS spec). <code>onResult</code>
/// is deferred until <code>KycViewController</code> has actually been dismissed
/// (<code>notifyViewControllerDismissed</code>, called from its <code>dismiss(animated:)</code>
/// completion) whenever a screen was shown at all — see <code>onFlowStateChanged</code>.
/// <code>@objc</code> + <code>NSObject</code> added directly onto this same class — same
/// mechanism v2 uses for <code>OEGManager</code>/<code>OegSdkCore</code>
/// (<code>Core/Public/OEGManager.swift</code>, <code>Core/Public/OegSdkCore.swift</code>): no
/// separate ObjC-facing facade class, <code>@objc</code> annotations live right on
/// the existing public members. Every member already ObjC-representable
/// (<code>String</code>/<code>String?</code>/<code>Bool</code>/closures of those) just gets <code>@objc</code>
/// directly; the two members that were not representable at all
/// (<code>initialize(_:)</code> takes a struct, <code>show(from:listener:)</code> takes a
/// protocol carrying an enum-with-payload) get a parallel <code>@objc</code> overload
/// instead of having their existing Swift signature changed — this
/// package’s public API is documented as frozen (design.md § Public API,
/// guarded by <code>PublicSurfaceTests.swift</code>), unlike v2 which had no prior
/// Swift-only surface to preserve.
SWIFT_CLASS("_TtC13AlogameKycKit13AlogameKycSdk")
@interface AlogameKycSdk : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AlogameKycSdk * _Nonnull shared;)
+ (AlogameKycSdk * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Objective-C-facing overload — <code>AlogameKycConfig</code> is a <code>struct</code>
/// (can’t cross the bridge at all), so this takes the same two fields
/// as plain, ObjC-representable parameters instead and builds the
/// config internally. Behaves identically to <code>initialize(_:)</code>.
- (void)initializeWithEnv:(enum AlogameKycEnv)env tokenProvider:(void (^ _Nullable)(NSString * _Nonnull, void (^ _Nonnull)(NSString * _Nullable)))tokenProvider;
/// <code>uid</code> and <code>sessionToken</code> are required together — they always arrive
/// from the same game-server response. Switching to a different <code>uid</code>
/// clears the verified cache and the prefill name for the old one — see
/// <code>SessionHolder.setGameRole</code>.
- (void)setGameRoleWithUid:(NSString * _Nonnull)uid sessionToken:(NSString * _Nonnull)sessionToken serverId:(NSString * _Nullable)serverId roleId:(NSString * _Nullable)roleId;
/// In-memory only — never written to disk, never sent anywhere except to
/// <code>ekycx</code> at the collect step, and only after the player has seen and
/// could edit it. Cleared when <code>uid</code> changes.
/// <code>ASAuthorizationAppleIDCredential.fullName</code> arrives only on the
/// <em>first</em> authorize for a given Apple ID — capture it there or it is
/// gone until the user revokes the app in Settings.
- (void)setPrefill:(NSString * _Nullable)fullName;
/// RAM cache of the most recent successful flow for the current uid —
/// <em>not</em> an authorization source. The game server must call
/// <code>POST /xmdt/user-status</code> before trusting that a player has verified;
/// a modified client can make this return whatever it wants.
@property (nonatomic, readonly) BOOL isVerified;
/// Delegates to the pending token request, if any. Ignored (not thrown) when nothing is awaiting a token.
- (void)provideSessionToken:(NSString * _Nonnull)token;
/// Delegates to the pending token request, if any — resolves it as <code>.sessionUnavailable</code>.
- (void)abortPendingToken;
/// Objective-C-facing overload — <code>AlogameKycListener</code> can’t cross the
/// bridge itself (<code>onResult</code> carries <code>AlogameKycResult</code>, an enum with
/// associated values), so this wraps <code>objcListener</code> in
/// <code>ObjcListenerAdapter</code> and calls the exact same <code>show(from:listener:)</code>
/// above. No behavior lives here beyond that translation.
- (void)showFromViewController:(UIViewController * _Nonnull)viewController objcListener:(id <AlogameKycObjcListener> _Nonnull)objcListener;
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
